name: build

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout new change
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: true
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: codgician
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --all-systems
      - run: nix build 
